base_url = "https://choique.org"
title = "Choique"
description = ""
theme="mabuya"

compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
build_search_index = true
taxonomies = [{ name = "tags", feed = true }]
default_language = "es"

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
smart_punctuation = true

[extra]
author = "Choique"
email = "contact@choique.org"
timeformat = "%B %e, %Y"

[[extra.menu]]
name = "Inicio"
url = "/"

[[extra.menu]]
name = "Acerca de"
url = "acerca-de"

[[extra.menu]]
name = "Proyectos"
url = "proyectos"

[[extra.menu]]
name = "Contacto"
url = "contacto"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a>.'

[languages.en]
generate_feeds = true
build_search_index = true
taxonomies = [
    {name = "autor"},
    {name = "tags"},
]

[languages.en.translations]
summary = "Blog"
